### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by zlimez**
- [X] Handle empty keyword for find and findcom
- [X] Modify error message for find
- [X] Remove allcom, anycom, allcus, anycus
- [X] findcom commission select issue @seelengxd 
- [X] Update UG Quickstart (images) and GUI alt for add commands

### CODE REVIEW

**Comment by zlimez** [comment]
@ngxingyu @seelengxd allcom works fine after findcom on my run?

**Comment by ngxingyu** [comment]
> @ngxingyu @seelengxd allcom works fine after findcom on my run?

The issue was `allcom` did not reset the predicate applied by `findcom` so it doesn't show all commissions, but I made a fix here: fd8c8808b7f624ec084355597afbba6e7c9ab7d4

**Comment by chloeelim** [comment]
Could you resolve the merge conflict in the UG? I've updated the quick start already so actually I think you can just follow the changes in master for the quick start section(?)

**Comment by zlimez** [comment]
> Could you resolve the merge conflict in the UG? I've updated the quick start already so actually I think you can just follow the changes in master for the quick start section(?)

Done

**Review by chloeelim — APPROVED** [review]

**Pull request merged**
