### PR TITLE
Add test for UniqueCommissionList

### PR DESCRIPTION
**Pull request by ngxingyu**
Add `CommissionBuilder` to help with tests.

Enforce non-null customer within commissions

- Previously customer could be `null` due to implementation of `JsonAdaptedCustomer` requiring the customer to be set after the instance was created.
- To avoid null pointer exceptions and since all commissions has customers, the Customer field for all commissions must be non-null.

Modify AddCommissionCommand to return the customer builder instead of the customer, since the selected customer is only known when `execute` is called.
- Note that the result displayed when performing any commission commands now prints the CommissionBuilder (without the customer) instead of the entire Commission

Add more tests to ParserUtilTest
- the 2 methods involving dates are not yet tested.

### CODE REVIEW

**Review by seelengxd — DISMISSED** [review]
LGTM! (didn't know test instances were reinitialized for each test and that's why this works :O) 

# I suspect there may be merge conflicts to fix (since commissions now uses a `CommissionBuilder` after the addcom pr)

**Review by seelengxd — CHANGES_REQUESTED** [review]
Looks mostly good, but needs to merge master and use the CommissionBuilder instead for the test `CommissionBuilder#build()`

**Review by chloeelim — DISMISSED** [review]
LGTM, thanks for the good work! Just check that the `CommissionBuilder#build` works with master because that method was removed in James' `addcom` PR as @seelengxd mentioned.

**Comment by ngxingyu** [comment]
Will look at this after #82 is merged since that's going to affect this pr as well

**Review by seelengxd — APPROVED** [review]
LGTM!

**Pull request merged**
